# Making SINGLE edits in the editing sequence

In [1]:
import pandas as pd
from itertools import permutations
from itertools import combinations

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [15]:
ifnb_df = pd.read_csv('/Users/hyominseo/Desktop/RAJ_RNA_Editing/MFE/Edited_fasta/Edited_All_MPRA_IFNb_Ed_Sites.tsv',sep='\t')
print("Row count:", ifnb_df.shape[0])
print("Count of unique 'Gene':")
print(ifnb_df['Gene'].value_counts())

ifnb_df= ifnb_df.groupby('Gene').apply(lambda x: x.sort_values('Edited_seq_num')).reset_index(drop=True)
ifnb_df.iloc[:5]

Row count: 283
Count of unique 'Gene':
MRPL30      8
MED18       8
PSMB2       8
TMEM170A    6
APOL1       5
GBP4        5
CTSS        5
GATC        5
IGSF6       5
CTSB        5
AHR         5
ARPIN       4
CGAS        4
SGTB        4
SH3BP2      4
PGPEP1      4
METTL7A     4
HOOK3       4
GNB4        4
CFLAR       4
CASP10      4
CYP20A1     4
CCNYL1      4
APOL6       4
LRCH3       3
ADGRE2      3
NBPF14      3
TMEM106A    3
RSPH3       3
EIF2AK2     3
ZNF101      3
MAGT1       3
ACOT9       3
ARSD        3
GPR157      3
ZYG11B      3
TTC39B      2
PHAX        2
NMNAT1      2
PRKAR2A     2
KIAA1143    2
MRI1        2
GSR         2
INPP5B      2
VPS41       2
PRR11       2
SOAT1       2
VHL         2
CEBPZOS     2
GNL3L       2
RBBP9       2
IL17RA      2
SNRPD3      2
NBPF20      2
ARHGAP26    2
ABHD18      2
CWF19L1     2
SSH1        2
ERO1A       2
MDM2        2
SLC12A6     2
IRAK4       2
PLBD2       2
SPN         2
CRCP        2
CENPN       2
MSR1        1
ZBTB24      1
DESI1       1
ERAP1       1
METTL2B     1
NFAM1       1
GPR141      1
RBM28       1
TRIM56      1
SLC17A5     1
KIAA0930    1
NXPE3       1
GINM1       1
TMED4       1
RBSN        1
ADAM19      1
LYN         1
SSR3        1
TRIM38      1
PPIA        1
PLEKHA2     1
NUP43       1
APOBEC3F    1
NBPF15      1
APOBEC3C    1
KCNE3       1
MRPS11      1
PIGBOS1     1
TMOD3       1
ALDH6A1     1
SNAPC1      1
BRCA2       1
MPHOSPH8    1
BCAT1       1
NDUFC2      1
CAMK1D      1
TPST2       1
LZIC        1
H6PD        1
RBMXL1      1
ICMT        1
PHACTR4     1
MDM4        1
NIBAN1      1
SLC35E2B    1
F11R        1
DCUN1D3     1
UBALD1      1
LONP2       1
EXOSC6      1
IFNAR2      1
YIPF4       1
SGPP2       1
CXCR2       1
CASP8       1
POLR2D      1
ZNF587B     1
BORCS8      1
ZNF844      1
TIMM29      1
ZNF397      1
MCRIP1      1
ACOX1       1
PSMD12      1
FBXL20      1
METTL16     1
LGALS9B     1
TRAPPC2L    1
DDX19A      1
PVR         1
Name: Gene, dtype: int64

,Gene,Chr,Start,End,ESid,Location,Raw_Index,Edited_Index,Edited_seq_num,Gene_Frequency,Strand,Name,Fasta_seq
0,NBPF15,chr1,144421990,144422291,chr1:144422141:A:G,144422141,A,G,151,1,(-),chr1:144422141:A:G,TCGGTCTGTCGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTG...
1,NBPF14,chr1,148531982,148532283,chr1:148532133:A:G,148532133,A,G,151,3,(-),chr1:148532133:A:G,TCGGTCTGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTG...
2,NBPF14,chr1,148531988,148532289,chr1:148532139:A:G,148532139,A,G,151,3,(-),chr1:148532139:A:G,TGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTGGTAGGT...
3,NBPF14,chr1,148532058,148532359,chr1:148532209:A:G,148532209,A,G,151,3,(-),chr1:148532209:A:G,TATAAACCCCAAGTTTTATTGATTTCTTTACGTCGATGTAATAGAA...
4,NBPF20,chr1,149054639,149054940,chr1:149054790:A:G,149054790,A,G,151,2,(-),chr1:149054790:A:G,TGTCGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTGGTAGGT...

In [2]:
lps_df = pd.read_csv('/Users/hyominseo/Desktop/RAJ_RNA_Editing/MFE/Edited_fasta/Edited_All_MPRA_LPS_Ed_Sites.tsv',sep='\t')
print("Row count:", lps_df.shape[0])
print("Count of unique 'Gene':")
print(lps_df['Gene'].value_counts())

lps_df= lps_df.groupby('Gene').apply(lambda x: x.sort_values('Edited_seq_num')).reset_index(drop=True)
lps_df.iloc[:5]

Row count: 157
Count of unique 'Gene':
PSMB2       7
TMEM170A    6
IGSF6       5
CTSB        5
AHR         5
           ..
DESI1       1
NFAM1       1
METTL6      1
CAMK1D      1
ZNF587B     1
Name: Gene, Length: 83, dtype: int64

,Gene,Chr,Start,End,ESid,Location,Raw_Index,Edited_Index,Edited_seq_num,Gene_Frequency,Strand,Name,Fasta_seq
0,NBPF14,chr1,148531982,148532283,chr1:148532133:A:G,148532133,A,G,151,2,(-),chr1:148532133:A:G,TCGGTCTGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTG...
1,NBPF14,chr1,148531988,148532289,chr1:148532139:A:G,148532139,A,G,151,2,(-),chr1:148532139:A:G,TGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTGGTAGGT...
2,NBPF20,chr1,149054642,149054943,chr1:149054793:A:G,149054793,A,G,151,1,(-),chr1:149054793:A:G,CGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTGGTAGGTACT...
3,CTSS,chr1,150730985,150731286,chr1:150731136:A:G,150731136,A,G,151,4,(-),chr1:150731136:A:G,ATTCTTCCGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTG...
4,CTSS,chr1,150730992,150731293,chr1:150731143:A:G,150731143,A,G,151,4,(-),chr1:150731143:A:G,CGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTGGGTACAA...

In [16]:
ifnb_df['Raw_seq'] = ifnb_df['Fasta_seq']
ifnb_df['Edited_seq'] = ifnb_df['Raw_seq']

In [3]:
lps_df['Raw_seq'] = lps_df['Fasta_seq']
lps_df['Edited_seq'] = lps_df['Raw_seq']

In [17]:
ifnb_df = ifnb_df[['Gene','Chr','Start','End','Name','Gene_Frequency','Edited_seq_num',
                                'Edited_Index','Raw_seq']]

In [4]:
lps_df = lps_df[['Gene','Chr','Start','End','Name','Gene_Frequency','Edited_seq_num',
                                'Edited_Index','Raw_seq']]

In [18]:
ifnb_df.iloc[:10]

,Gene,Chr,Start,End,Name,Gene_Frequency,Edited_seq_num,Edited_Index,Raw_seq
0,NBPF15,chr1,144421990,144422291,chr1:144422141:A:G,1,151,G,TCGGTCTGTCGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTG...
1,NBPF14,chr1,148531982,148532283,chr1:148532133:A:G,3,151,G,TCGGTCTGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTG...
2,NBPF14,chr1,148531988,148532289,chr1:148532139:A:G,3,151,G,TGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTGGTAGGT...
3,NBPF14,chr1,148532058,148532359,chr1:148532209:A:G,3,151,G,TATAAACCCCAAGTTTTATTGATTTCTTTACGTCGATGTAATAGAA...
4,NBPF20,chr1,149054639,149054940,chr1:149054790:A:G,2,151,G,TGTCGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTGGTAGGT...
5,NBPF20,chr1,149054642,149054943,chr1:149054793:A:G,2,151,G,CGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTGGTAGGTACT...
6,CTSS,chr1,150730985,150731286,chr1:150731136:A:G,5,151,G,ATTCTTCCGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTG...
7,CTSS,chr1,150730992,150731293,chr1:150731143:A:G,5,151,G,CGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTGGGTACAA...
8,CTSS,chr1,150731785,150732086,chr1:150731936:A:G,5,151,G,ACAACTACTGATGCATTTTTATTAAACCTGATTATGTAATTTAACA...
9,CTSS,chr1,150731958,150732259,chr1:150732109:A:G,5,151,G,ACGTCACCACGTTAATGTTCGAGTGACGTAAGAGTTGGAGGACCCG...

In [5]:
lps_df.iloc[:5]

,Gene,Chr,Start,End,Name,Gene_Frequency,Edited_seq_num,Edited_Index,Raw_seq
0,NBPF14,chr1,148531982,148532283,chr1:148532133:A:G,2,151,G,TCGGTCTGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTG...
1,NBPF14,chr1,148531988,148532289,chr1:148532139:A:G,2,151,G,TGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTGGTAGGT...
2,NBPF20,chr1,149054642,149054943,chr1:149054793:A:G,1,151,G,CGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTGGTAGGTACT...
3,CTSS,chr1,150730985,150731286,chr1:150731136:A:G,4,151,G,ATTCTTCCGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTG...
4,CTSS,chr1,150730992,150731293,chr1:150731143:A:G,4,151,G,CGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTGGGTACAA...

In [19]:
pd.set_option('display.max_rows', ifnb_df.shape[0])
print(ifnb_df)

         Gene    Chr      Start        End                 Name  \
0      NBPF15   chr1  144421990  144422291   chr1:144422141:A:G
1      NBPF14   chr1  148531982  148532283   chr1:148532133:A:G
2      NBPF14   chr1  148531988  148532289   chr1:148532139:A:G
3      NBPF14   chr1  148532058  148532359   chr1:148532209:A:G
4      NBPF20   chr1  149054639  149054940   chr1:149054790:A:G
5      NBPF20   chr1  149054642  149054943   chr1:149054793:A:G
6        CTSS   chr1  150730985  150731286   chr1:150731136:A:G
7        CTSS   chr1  150730992  150731293   chr1:150731143:A:G
8        CTSS   chr1  150731785  150732086   chr1:150731936:A:G
9        CTSS   chr1  150731958  150732259   chr1:150732109:A:G
10       CTSS   chr1  150732621  150732922   chr1:150732772:A:G
11       F11R   chr1  160997892  160998193   chr1:160998043:A:G
12   SLC35E2B   chr1    1663996    1664297     chr1:1664147:A:G
13      SOAT1   chr1  179357488  179357789   chr1:179357639:A:G
14      SOAT1   chr1  179357593  179357894   chr1:179357744:A:G
15     NIBAN1   chr1  184792027  184792328   chr1:184792178:A:G
16       MDM4   chr1  204556370  204556671   chr1:204556521:A:G
17      MED18   chr1   28334914   28335215    chr1:28335065:A:G
18      MED18   chr1   28335020   28335321    chr1:28335171:A:G
19      MED18   chr1   28335030   28335331    chr1:28335181:A:G
20      MED18   chr1   28335032   28335333    chr1:28335183:A:G
21      MED18   chr1   28335057   28335358    chr1:28335208:A:G
22      MED18   chr1   28335537   28335838    chr1:28335688:A:G
23      MED18   chr1   28335550   28335851    chr1:28335701:A:G
24      MED18   chr1   28335551   28335852    chr1:28335702:A:G
25    PHACTR4   chr1   28499422   28499723    chr1:28499573:A:G
26      PSMB2   chr1   35599752   35600053    chr1:35599903:A:G
27      PSMB2   chr1   35601925   35602226    chr1:35602076:A:G
28      PSMB2   chr1   35602086   35602387    chr1:35602237:A:G
29      PSMB2   chr1   35602443   35602744    chr1:35602594:A:G
30      PSMB2   chr1   35602458   35602759    chr1:35602609:A:G
31      PSMB2   chr1   35602524   35602825    chr1:35602675:A:G
32      PSMB2   chr1   35602573   35602874    chr1:35602724:A:G
33      PSMB2   chr1   35602618   35602919    chr1:35602769:A:G
34     INPP5B   chr1   37860905   37861206    chr1:37861056:A:G
35     INPP5B   chr1   37861877   37862178    chr1:37862028:A:G
36     ZYG11B   chr1   52823039   52823340    chr1:52823190:A:G
37     ZYG11B   chr1   52823101   52823402    chr1:52823252:A:G
38     ZYG11B   chr1   52823936   52824237    chr1:52824087:A:G
39       ICMT   chr1    6222013    6222314     chr1:6222164:A:G
40     RBMXL1   chr1   88981886   88982187    chr1:88982037:C:T
41       GBP4   chr1   89183535   89183836    chr1:89183686:A:G
42       GBP4   chr1   89183688   89183989    chr1:89183839:A:G
43       GBP4   chr1   89183715   89184016    chr1:89183866:A:G
44       GBP4   chr1   89183723   89184024    chr1:89183874:A:G
45       GBP4   chr1   89183726   89184027    chr1:89183877:A:G
46     GPR157   chr1    9100779    9101080     chr1:9100930:A:G
47     GPR157   chr1    9100993    9101294     chr1:9101144:A:G
48     GPR157   chr1    9101008    9101309     chr1:9101159:A:G
49       H6PD   chr1    9268032    9268333     chr1:9268183:A:G
50       LZIC   chr1    9928482    9928783     chr1:9928633:A:G
51     NMNAT1   chr1    9982728    9983029     chr1:9982879:A:G
52     NMNAT1   chr1    9982844    9983145     chr1:9982995:A:G
53    CWF19L1  chr10  100232902  100233203  chr10:100233053:A:G
54    CWF19L1  chr10  100232991  100233292  chr10:100233142:A:G
55     CAMK1D  chr10   12825907   12826208   chr10:12826058:A:G
56      KCNE3  chr11   74456098   74456399   chr11:74456249:A:G
57     NDUFC2  chr11   78069028   78069329   chr11:78069179:A:G
58       SSH1  chr12  108786492  108786793  chr12:108786643:A:G
59       SSH1  chr12  108786497  108786798  chr12:108786648:A:G
60      PLBD2  chr12  113390968  113391269  chr12:113391119:A:G
61      PLBD2  chr12  113390969  113391270  chr12:113391120:A:G
62       GATC  chr12  120460599  120460900  chr12:120460750:A:G
63       GATC  chr12  120460707  120461008  chr12:120460858:A:G
64       GATC  chr12  120460743  120461044  chr12:120460894:A:G
65       GATC  chr12  120460775  120461076  chr12:120460926:A:G
66       GATC  chr12  120460989  120461290  chr12:120461140:A:G
67      BCAT1  chr12   24816736   24817037   chr12:24816887:A:G
68      IRAK4  chr12   43787785   43788086   chr12:43787936:A:G
69      IRAK4  chr12   43787820   43788121   chr12:43787971:A:G
70    METTL7A  chr12   50930188   50930489   chr12:50930339:A:G
71    METTL7A  chr12   50930532   50930833   chr12:50930683:A:G
72    METTL7A  chr12   50930533   50930834   chr12:50930684:A:G
73    METTL7A  chr12   50931372   50931673   chr12:50931523:A:G
74       MDM2  chr12   68843122   68843423   chr12:68843273:A:G
75       MDM2  chr12   68843621   68843922   chr12:68843772:A:G
76   MPHOSPH8  chr13   19672111   19672412   chr13:19672262:A:G
77      BRCA2  chr13   32398912   32399213   chr13:32399063:A:G
78      ERO1A  chr14   52642941   52643242   chr14:52643092:A:G
79      ERO1A  chr14   52642954   52643255   chr14:52643105:A:G
80     SNAPC1  chr14   61795743   61796044   chr14:61795894:A:G
81    ALDH6A1  chr14   74057932   74058233   chr14:74058083:A:G
82    SLC12A6  chr15   34232304   34232605   chr15:34232455:A:G
83    SLC12A6  chr15   34232356   34232657   chr15:34232507:A:G
84      TMOD3  chr15   51913787   51914088   chr15:51913938:A:G
85    PIGBOS1  chr15   55317301   55317602   chr15:55317452:A:G
86     MRPS11  chr15   88478579   88478880   chr15:88478730:A:G
87      ARPIN  chr15   89897186   89897487   chr15:89897337:A:G
88      ARPIN  chr15   89897212   89897513   chr15:89897363:A:G
89      ARPIN  chr15   89897271   89897572   chr15:89897422:A:G
90      ARPIN  chr15   89897277   89897578   chr15:89897428:A:G
91    DCUN1D3  chr16   20856045   20856346   chr16:20856196:A:G
92      IGSF6  chr16   21639864   21640165   chr16:21640015:A:G
93      IGSF6  chr16   21639935   21640236   chr16:21640086:A:G
94      IGSF6  chr16   21640059   21640360   chr16:21640210:A:G
95      IGSF6  chr16   21640343   21640644   chr16:21640494:A:G
96      IGSF6  chr16   21640507   21640808   chr16:21640658:A:G
97        SPN  chr16   29667372   29667673   chr16:29667523:A:G
98        SPN  chr16   29670087   29670388   chr16:29670238:A:G
99     UBALD1  chr16    4609204    4609505    chr16:4609355:C:T
100     LONP2  chr16   48354320   48354621   chr16:48354471:A:G
101    EXOSC6  chr16   70249164   70249465   chr16:70249315:A:G
102    DDX19A  chr16   70372824   70373125   chr16:70372975:A:G
103  TMEM170A  chr16   75445282   75445583   chr16:75445433:A:G
104  TMEM170A  chr16   75445435   75445736   chr16:75445586:A:G
105  TMEM170A  chr16   75445782   75446083   chr16:75445933:A:G
106  TMEM170A  chr16   75445783   75446084   chr16:75445934:A:G
107  TMEM170A  chr16   75445858   75446159   chr16:75446009:A:G
108  TMEM170A  chr16   75445961   75446262   chr16:75446112:A:G
109     CENPN  chr16   81030478   81030779   chr16:81030629:A:G
110     CENPN  chr16   81030580   81030881   chr16:81030731:A:G
111  TRAPPC2L  chr16   88862391   88862692   chr16:88862542:A:G
112   LGALS9B  chr17   20449445   20449746   chr17:20449596:A:G
113   METTL16  chr17    2417064    2417365    chr17:2417215:A:G
114    FBXL20  chr17   39256997   39257298   chr17:39257148:A:G
115  TMEM106A  chr17   43218254   43218555   chr17:43218405:A:G
116  TMEM106A  chr17   43218290   43218591   chr17:43218441:A:G
117  TMEM106A  chr17   43218390   43218691   chr17:43218541:A:G
118     PRR11  chr17   59203543   59203844   chr17:59203694:A:G
119     PRR11  chr17   59203547   59203848   chr17:59203698:A:G
120    PSMD12  chr17   67338458   67338759   chr17:67338609:A:G
121     ACOX1  chr17   75944867   75945168   chr17:75945018:A:G
122    MCRIP1  chr17   81822665   81822966   chr17:81822816:A:G
123    ZNF397  chr18   35248508   35248809   chr18:35248659:A:G
124    TIMM29  chr19   10929979   10930280   chr19:10930130:A:G
125    ZNF844  chr19   12080824   12081125   chr19:12080975:A:G
126      MRI1  chr19   13773560   13773861   chr19:13773711:A:G
127      MRI1  chr19   13773607   13773908   chr19:13773758:A:G
128    ADGRE2  chr19   14734173   14734474   chr19:14734324:A:G
129    ADGRE2  chr19   14734509   14734810   chr19:14734660:A:G
130    ADGRE2  chr19   14734549   14734850   chr19:14734700:A:G
131    PGPEP1  chr19   18365245   18365546   chr19:18365396:A:G
132    PGPEP1  chr19   18366368   18366669   chr19:18366519:A:G
133    PGPEP1  chr19   18366449   18366750   chr19:18366600:A:G
134    PGPEP1  chr19   18366940   18367241   chr19:18367091:A:G
135    BORCS8  chr19   19177244   19177545   chr19:19177395:A:G
136    ZNF101  chr19   19682820   19683121   chr19:19682971:A:G
137    ZNF101  chr19   19682915   19683216   chr19:19683066:A:G
138    ZNF101  chr19   19682916   19683217   chr19:19683067:A:G
139       PVR  chr19   44663703   44664004   chr19:44663854:A:G
140   ZNF587B  chr19   57845749   57846050   chr19:57845900:A:G
141    POLR2D   chr2  127845935  127846236   chr2:127846086:A:G
142     CFLAR   chr2  201163853  201164154   chr2:201164004:A:G
143     CFLAR   chr2  201163859  201164160   chr2:201164010:A:G
144     CFLAR   chr2  201165220  201165521   chr2:201165371:A:G
145     CFLAR   chr2  201165395  201165696   chr2:201165546:A:G
146    CASP10   chr2  201217888  201218189   chr2:201218039:A:G
147    CASP10   chr2  201218183  201218484   chr2:201218334:A:G
148    CASP10   chr2  201218361  201218662   chr2:201218512:A:G
149    CASP10   chr2  201218371  201218672   chr2:201218522:A:G
150     CASP8   chr2  201287188  201287489   chr2:201287339:A:G
151   CYP20A1   chr2  203297723  203298024   chr2:203297874:A:G
152   CYP20A1   chr2  203300519  203300820   chr2:203300670:A:G
153   CYP20A1   chr2  203300618  203300919   chr2:203300769:A:G
154   CYP20A1   chr2  203305311  203305612   chr2:203305462:A:G
155    CCNYL1   chr2  207754586  207754887   chr2:207754737:A:G
156    CCNYL1   chr2  207754616  207754917   chr2:207754767:A:G
157    CCNYL1   chr2  207754800  207755101   chr2:207754951:A:G
158    CCNYL1   chr2  207754867  207755168   chr2:207755018:A:G
159     CXCR2   chr2  218135740  218136041   chr2:218135891:C:T
160     SGPP2   chr2  222559364  222559665   chr2:222559515:A:G
161     YIPF4   chr2   32310528   32310829    chr2:32310679:A:G
162   EIF2AK2   chr2   37100788   37101089    chr2:37100939:A:G
163   EIF2AK2   chr2   37100803   37101104    chr2:37100954:A:G
164   EIF2AK2   chr2   37103744   37104045    chr2:37103895:A:G
165   CEBPZOS   chr2   37202333   37202634    chr2:37202484:A:G
166   CEBPZOS   chr2   37202383   37202684    chr2:37202534:A:G
167    MRPL30   chr2   99195675   99195976    chr2:99195826:A:G
168    MRPL30   chr2   99195850   99196151    chr2:99196001:A:G
169    MRPL30   chr2   99196194   99196495    chr2:99196345:A:G
170    MRPL30   chr2   99196201   99196502    chr2:99196352:A:G
171    MRPL30   chr2   99196203   99196504    chr2:99196354:A:G
172    MRPL30   chr2   99196243   99196544    chr2:99196394:A:G
173    MRPL30   chr2   99196364   99196665    chr2:99196515:A:G
174    MRPL30   chr2   99196374   99196675    chr2:99196525:A:G
175     RBBP9  chr20   18487679   18487980   chr20:18487830:A:G
176     RBBP9  chr20   18488292   18488593   chr20:18488443:A:G
177    IFNAR2  chr21   33263905   33264206   chr21:33264056:A:G
178    IL17RA  chr22   17110226   17110527   chr22:17110377:A:G
179    IL17RA  chr22   17113117   17113418   chr22:17113268:A:G
180    SNRPD3  chr22   24573681   24573982   chr22:24573832:A:G
181    SNRPD3  chr22   24574423   24574724   chr22:24574574:A:G
182     TPST2  chr22   26523613   26523914   chr22:26523764:A:G
183     APOL6  chr22   35659740   35660041   chr22:35659891:A:G
184     APOL6  chr22   35660400   35660701   chr22:35660551:A:G
185     APOL6  chr22   35661053   35661354   chr22:35661204:A:G
186     APOL6  chr22   35661157   35661458   chr22:35661308:A:G
187     APOL1  chr22   36266069   36266370   chr22:36266220:A:G
188     APOL1  chr22   36266120   36266421   chr22:36266271:A:G
189     APOL1  chr22   36266199   36266500   chr22:36266350:A:G
190     APOL1  chr22   36266200   36266501   chr22:36266351:A:G
191     APOL1  chr22   36266592   36266893   chr22:36266743:A:G
192  APOBEC3C  chr22   39019735   39020036   chr22:39019886:A:G
193  APOBEC3F  chr22   39053367   39053668   chr22:39053518:A:G
194     DESI1  chr22   41599105   41599406   chr22:41599256:A:G
195     NFAM1  chr22   42383383   42383684   chr22:42383534:A:G
196  KIAA0930  chr22   45194257   45194558   chr22:45194408:A:G
197       VHL   chr3   10150949   10151250    chr3:10151100:A:G
198       VHL   chr3   10150981   10151282    chr3:10151132:A:G
199     NXPE3   chr3  101823441  101823742   chr3:101823592:A:G
200      RBSN   chr3   15072828   15073129    chr3:15072979:A:G
201      SSR3   chr3  156541423  156541724   chr3:156541574:A:G
202      GNB4   chr3  179399216  179399517   chr3:179399367:A:G
203      GNB4   chr3  179399225  179399526   chr3:179399376:A:G
204      GNB4   chr3  179399325  179399626   chr3:179399476:A:G
205      GNB4   chr3  179399327  179399628   chr3:179399478:A:G
206     LRCH3   chr3  197884189  197884490   chr3:197884340:A:G
207     LRCH3   chr3  197885198  197885499   chr3:197885349:A:G
208     LRCH3   chr3  197885246  197885547   chr3:197885397:A:G
209  KIAA1143   chr3   44748993   44749294    chr3:44749144:A:G
210  KIAA1143   chr3   44749754   44750055    chr3:44749905:A:G
211   PRKAR2A   chr3   48749458   48749759    chr3:48749609:A:G
212   PRKAR2A   chr3   48750272   48750573    chr3:48750423:A:G
213    ABHD18   chr4  128036424  128036725   chr4:128036575:A:G
214    ABHD18   chr4  128036779  128037080   chr4:128036930:A:G
215    SH3BP2   chr4    2839474    2839775     chr4:2839625:A:G
216    SH3BP2   chr4    2839510    2839811     chr4:2839661:A:G
217    SH3BP2   chr4    2839923    2840224     chr4:2840074:A:G
218    SH3BP2   chr4    2839967    2840268     chr4:2840118:A:G
219      PHAX   chr5  126625780  126626081   chr5:126625931:A:G
220      PHAX   chr5  126626332  126626633   chr5:126626483:A:G
221  ARHGAP26   chr5  143225101  143225402   chr5:143225252:A:G
222  ARHGAP26   chr5  143225290  143225591   chr5:143225441:A:G
223    ADAM19   chr5  157478401  157478702   chr5:157478552:A:G
224      SGTB   chr5   65668074   65668375    chr5:65668225:A:G
225      SGTB   chr5   65668348   65668649    chr5:65668499:A:G
226      SGTB   chr5   65668705   65669006    chr5:65668856:A:G
227      SGTB   chr5   65668740   65669041    chr5:65668891:A:G
228     ERAP1   chr5   96774689   96774990    chr5:96774840:A:G
229    ZBTB24   chr6  109462932  109463233   chr6:109463083:A:G
230     GINM1   chr6  149591020  149591321   chr6:149591171:A:G
231     NUP43   chr6  149724469  149724770   chr6:149724620:A:G
232     RSPH3   chr6  158974177  158974478   chr6:158974328:A:G
233     RSPH3   chr6  158974182  158974483   chr6:158974333:A:G
234     RSPH3   chr6  158974238  158974539   chr6:158974389:A:G
235    TRIM38   chr6   25990285   25990586    chr6:25990436:A:G
236      CGAS   chr6   73424840   73425141    chr6:73424991:A:G
237      CGAS   chr6   73424880   73425181    chr6:73425031:A:G
238      CGAS   chr6   73424885   73425186    chr6:73425036:A:G
239      CGAS   chr6   73424974   73425275    chr6:73425125:A:G
240   SLC17A5   chr6   73594139   73594440    chr6:73594290:A:G
241    TRIM56   chr7  101091366  101091667   chr7:101091517:A:G
242     RBM28   chr7  128307775  128308076   chr7:128307926:A:G
243   METTL2B   chr7  128502628  128502929   chr7:128502779:A:G
244       AHR   chr7   17344620   17344921    chr7:17344771:A:G
245       AHR   chr7   17344910   17345211    chr7:17345061:A:G
246       AHR   chr7   17344988   17345289    chr7:17345139:A:G
247       AHR   chr7   17345008   17345309    chr7:17345159:A:G
248       AHR   chr7   17345105   17345406    chr7:17345256:A:G
249    GPR141   chr7   37742668   37742969    chr7:37742819:A:G
250     VPS41   chr7   38724508   38724809    chr7:38724659:A:G
251     VPS41   chr7   38724571   38724872    chr7:38724722:A:G
252     TMED4   chr7   44580720   44581021    chr7:44580871:A:G
253      PPIA   chr7   44802178   44802479    chr7:44802329:A:G
254      CRCP   chr7   66154206   66154507    chr7:66154357:A:G
255      CRCP   chr7   66154209   66154510    chr7:66154360:A:G
256      CTSB   chr8   11842558   11842859    chr8:11842709:A:G
257      CTSB   chr8   11842936   11843237    chr8:11843087:A:G
258      CTSB   chr8   11843017   11843318    chr8:11843168:A:G
259      CTSB   chr8   11843769   11844070    chr8:11843920:A:G
260      CTSB   chr8   11843825   11844126    chr8:11843976:A:G
261      MSR1   chr8   16107995   16108296    chr8:16108146:A:G
262       GSR   chr8   30678307   30678608    chr8:30678458:A:G
263       GSR   chr8   30678312   30678613    chr8:30678463:A:G
264   PLEKHA2   chr8   38972169   38972470    chr8:38972320:A:G
265     HOOK3   chr8   43020432   43020733    chr8:43020583:A:G
266     HOOK3   chr8   43020442   43020743    chr8:43020593:A:G
267     HOOK3   chr8   43020774   43021075    chr8:43020925:A:G
268     HOOK3   chr8   43021252   43021553    chr8:43021403:A:G
269       LYN   chr8   56012445   56012746    chr8:56012596:A:G
270    TTC39B   chr9   15167178   15167479    chr9:15167329:A:G
271    TTC39B   chr9   15167539   15167840    chr9:15167690:A:G
272     ACOT9   chrX   23701520   23701821    chrX:23701671:A:G
273     ACOT9   chrX   23701756   23702057    chrX:23701907:A:G
274     ACOT9   chrX   23702386   23702687    chrX:23702537:A:G
275      ARSD   chrX    2906185    2906486     chrX:2906336:A:G
276      ARSD   chrX    2906282    2906583     chrX:2906433:A:G
277      ARSD   chrX    2906922    2907223     chrX:2907073:A:G
278     GNL3L   chrX   54562599   54562900    chrX:54562750:A:G
279     GNL3L   chrX   54564683   54564984    chrX:54564834:A:G
280     MAGT1   chrX   77827997   77828298    chrX:77828148:A:G
281     MAGT1   chrX   77828005   77828306    chrX:77828156:A:G
282     MAGT1   chrX   77828394   77828695    chrX:77828545:A:G

     Gene_Frequency  Edited_seq_num Edited_Index  \
0                 1             151            G
1                 3             151            G
2                 3             151            G
3                 3             151            G
4                 2             151            G
5                 2             151            G
6                 5             151            G
7                 5             151            G
8                 5             151            G
9                 5             151            G
10                5             151            G
11                1             151            G
12                1             151            G
13                2             151            G
14                2             151            G
15                1             151            G
16                1             151            G
17                8             151            G
18                8             151            G
19                8             151            G
20                8             151            G
21                8             151            G
22                8             151            G
23                8             151            G
24                8             151            G
25                1             151            G
26                8             151            G
27                8             151            G
28                8             151            G
29                8             151            G
30                8             151            G
31                8             151            G
32                8             151            G
33                8             151            G
34                2             151            G
35                2             151            G

In [6]:
# Adding number tag on all Gene to seperate them as invidiaual genes - stupid but trying
def make_unique_gene_names(df_in):
    df_out = df_in.copy()  # Create a copy of the input DataFrame
    
    # Group the DataFrame by the 'Gene' column
    grouped = df_out.groupby('Gene')
    
    # Iterate over each group
    for gene, group in grouped:
        # If there are duplicate gene names, add suffixes to make them unique
        if len(group) > 1:
            # Iterate over each row in the group
            for i, (_, row) in enumerate(group.iterrows(), start=1):
                # Append suffix to the gene name
                new_gene_name = f"{gene}-{i}"
                
                # Update the gene name in the DataFrame
                df_out.at[row.name, 'Gene'] = new_gene_name
    
    return df_out

In [21]:
ifnb_df_named = make_unique_gene_names(ifnb_df)
ifnb_df_named['Edited_seq'] = ifnb_df_named['Raw_seq']

pd.set_option('display.max_rows', ifnb_df_named.shape[0]+1)
print(ifnb_df_named)

           Gene    Chr      Start        End                 Name  \
0        NBPF15   chr1  144421990  144422291   chr1:144422141:A:G
1      NBPF14-1   chr1  148531982  148532283   chr1:148532133:A:G
2      NBPF14-2   chr1  148531988  148532289   chr1:148532139:A:G
3      NBPF14-3   chr1  148532058  148532359   chr1:148532209:A:G
4      NBPF20-1   chr1  149054639  149054940   chr1:149054790:A:G
5      NBPF20-2   chr1  149054642  149054943   chr1:149054793:A:G
6        CTSS-1   chr1  150730985  150731286   chr1:150731136:A:G
7        CTSS-2   chr1  150730992  150731293   chr1:150731143:A:G
8        CTSS-3   chr1  150731785  150732086   chr1:150731936:A:G
9        CTSS-4   chr1  150731958  150732259   chr1:150732109:A:G
10       CTSS-5   chr1  150732621  150732922   chr1:150732772:A:G
11         F11R   chr1  160997892  160998193   chr1:160998043:A:G
12     SLC35E2B   chr1    1663996    1664297     chr1:1664147:A:G
13      SOAT1-1   chr1  179357488  179357789   chr1:179357639:A:G
14      SOAT1-2   chr1  179357593  179357894   chr1:179357744:A:G
15       NIBAN1   chr1  184792027  184792328   chr1:184792178:A:G
16         MDM4   chr1  204556370  204556671   chr1:204556521:A:G
17      MED18-1   chr1   28334914   28335215    chr1:28335065:A:G
18      MED18-2   chr1   28335020   28335321    chr1:28335171:A:G
19      MED18-3   chr1   28335030   28335331    chr1:28335181:A:G
20      MED18-4   chr1   28335032   28335333    chr1:28335183:A:G
21      MED18-5   chr1   28335057   28335358    chr1:28335208:A:G
22      MED18-6   chr1   28335537   28335838    chr1:28335688:A:G
23      MED18-7   chr1   28335550   28335851    chr1:28335701:A:G
24      MED18-8   chr1   28335551   28335852    chr1:28335702:A:G
25      PHACTR4   chr1   28499422   28499723    chr1:28499573:A:G
26      PSMB2-1   chr1   35599752   35600053    chr1:35599903:A:G
27      PSMB2-2   chr1   35601925   35602226    chr1:35602076:A:G
28      PSMB2-3   chr1   35602086   35602387    chr1:35602237:A:G
29      PSMB2-4   chr1   35602443   35602744    chr1:35602594:A:G
30      PSMB2-5   chr1   35602458   35602759    chr1:35602609:A:G
31      PSMB2-6   chr1   35602524   35602825    chr1:35602675:A:G
32      PSMB2-7   chr1   35602573   35602874    chr1:35602724:A:G
33      PSMB2-8   chr1   35602618   35602919    chr1:35602769:A:G
34     INPP5B-1   chr1   37860905   37861206    chr1:37861056:A:G
35     INPP5B-2   chr1   37861877   37862178    chr1:37862028:A:G
36     ZYG11B-1   chr1   52823039   52823340    chr1:52823190:A:G
37     ZYG11B-2   chr1   52823101   52823402    chr1:52823252:A:G
38     ZYG11B-3   chr1   52823936   52824237    chr1:52824087:A:G
39         ICMT   chr1    6222013    6222314     chr1:6222164:A:G
40       RBMXL1   chr1   88981886   88982187    chr1:88982037:C:T
41       GBP4-1   chr1   89183535   89183836    chr1:89183686:A:G
42       GBP4-2   chr1   89183688   89183989    chr1:89183839:A:G
43       GBP4-3   chr1   89183715   89184016    chr1:89183866:A:G
44       GBP4-4   chr1   89183723   89184024    chr1:89183874:A:G
45       GBP4-5   chr1   89183726   89184027    chr1:89183877:A:G
46     GPR157-1   chr1    9100779    9101080     chr1:9100930:A:G
47     GPR157-2   chr1    9100993    9101294     chr1:9101144:A:G
48     GPR157-3   chr1    9101008    9101309     chr1:9101159:A:G
49         H6PD   chr1    9268032    9268333     chr1:9268183:A:G
50         LZIC   chr1    9928482    9928783     chr1:9928633:A:G
51     NMNAT1-1   chr1    9982728    9983029     chr1:9982879:A:G
52     NMNAT1-2   chr1    9982844    9983145     chr1:9982995:A:G
53    CWF19L1-1  chr10  100232902  100233203  chr10:100233053:A:G
54    CWF19L1-2  chr10  100232991  100233292  chr10:100233142:A:G
55       CAMK1D  chr10   12825907   12826208   chr10:12826058:A:G
56        KCNE3  chr11   74456098   74456399   chr11:74456249:A:G
57       NDUFC2  chr11   78069028   78069329   chr11:78069179:A:G
58       SSH1-1  chr12  108786492  108786793  chr12:108786643:A:G
59       SSH1-2  chr12  108786497  108786798  chr12:108786648:A:G
60      PLBD2-1  chr12  113390968  113391269  chr12:113391119:A:G
61      PLBD2-2  chr12  113390969  113391270  chr12:113391120:A:G
62       GATC-1  chr12  120460599  120460900  chr12:120460750:A:G
63       GATC-2  chr12  120460707  120461008  chr12:120460858:A:G
64       GATC-3  chr12  120460743  120461044  chr12:120460894:A:G
65       GATC-4  chr12  120460775  120461076  chr12:120460926:A:G
66       GATC-5  chr12  120460989  120461290  chr12:120461140:A:G
67        BCAT1  chr12   24816736   24817037   chr12:24816887:A:G
68      IRAK4-1  chr12   43787785   43788086   chr12:43787936:A:G
69      IRAK4-2  chr12   43787820   43788121   chr12:43787971:A:G
70    METTL7A-1  chr12   50930188   50930489   chr12:50930339:A:G
71    METTL7A-2  chr12   50930532   50930833   chr12:50930683:A:G
72    METTL7A-3  chr12   50930533   50930834   chr12:50930684:A:G
73    METTL7A-4  chr12   50931372   50931673   chr12:50931523:A:G
74       MDM2-1  chr12   68843122   68843423   chr12:68843273:A:G
75       MDM2-2  chr12   68843621   68843922   chr12:68843772:A:G
76     MPHOSPH8  chr13   19672111   19672412   chr13:19672262:A:G
77        BRCA2  chr13   32398912   32399213   chr13:32399063:A:G
78      ERO1A-1  chr14   52642941   52643242   chr14:52643092:A:G
79      ERO1A-2  chr14   52642954   52643255   chr14:52643105:A:G
80       SNAPC1  chr14   61795743   61796044   chr14:61795894:A:G
81      ALDH6A1  chr14   74057932   74058233   chr14:74058083:A:G
82    SLC12A6-1  chr15   34232304   34232605   chr15:34232455:A:G
83    SLC12A6-2  chr15   34232356   34232657   chr15:34232507:A:G
84        TMOD3  chr15   51913787   51914088   chr15:51913938:A:G
85      PIGBOS1  chr15   55317301   55317602   chr15:55317452:A:G
86       MRPS11  chr15   88478579   88478880   chr15:88478730:A:G
87      ARPIN-1  chr15   89897186   89897487   chr15:89897337:A:G
88      ARPIN-2  chr15   89897212   89897513   chr15:89897363:A:G
89      ARPIN-3  chr15   89897271   89897572   chr15:89897422:A:G
90      ARPIN-4  chr15   89897277   89897578   chr15:89897428:A:G
91      DCUN1D3  chr16   20856045   20856346   chr16:20856196:A:G
92      IGSF6-1  chr16   21639864   21640165   chr16:21640015:A:G
93      IGSF6-2  chr16   21639935   21640236   chr16:21640086:A:G
94      IGSF6-3  chr16   21640059   21640360   chr16:21640210:A:G
95      IGSF6-4  chr16   21640343   21640644   chr16:21640494:A:G
96      IGSF6-5  chr16   21640507   21640808   chr16:21640658:A:G
97        SPN-1  chr16   29667372   29667673   chr16:29667523:A:G
98        SPN-2  chr16   29670087   29670388   chr16:29670238:A:G
99       UBALD1  chr16    4609204    4609505    chr16:4609355:C:T
100       LONP2  chr16   48354320   48354621   chr16:48354471:A:G
101      EXOSC6  chr16   70249164   70249465   chr16:70249315:A:G
102      DDX19A  chr16   70372824   70373125   chr16:70372975:A:G
103  TMEM170A-1  chr16   75445282   75445583   chr16:75445433:A:G
104  TMEM170A-2  chr16   75445435   75445736   chr16:75445586:A:G
105  TMEM170A-3  chr16   75445782   75446083   chr16:75445933:A:G
106  TMEM170A-4  chr16   75445783   75446084   chr16:75445934:A:G
107  TMEM170A-5  chr16   75445858   75446159   chr16:75446009:A:G
108  TMEM170A-6  chr16   75445961   75446262   chr16:75446112:A:G
109     CENPN-1  chr16   81030478   81030779   chr16:81030629:A:G
110     CENPN-2  chr16   81030580   81030881   chr16:81030731:A:G
111    TRAPPC2L  chr16   88862391   88862692   chr16:88862542:A:G
112     LGALS9B  chr17   20449445   20449746   chr17:20449596:A:G
113     METTL16  chr17    2417064    2417365    chr17:2417215:A:G
114      FBXL20  chr17   39256997   39257298   chr17:39257148:A:G
115  TMEM106A-1  chr17   43218254   43218555   chr17:43218405:A:G
116  TMEM106A-2  chr17   43218290   43218591   chr17:43218441:A:G
117  TMEM106A-3  chr17   43218390   43218691   chr17:43218541:A:G
118     PRR11-1  chr17   59203543   59203844   chr17:59203694:A:G
119     PRR11-2  chr17   59203547   59203848   chr17:59203698:A:G
120      PSMD12  chr17   67338458   67338759   chr17:67338609:A:G
121       ACOX1  chr17   75944867   75945168   chr17:75945018:A:G
122      MCRIP1  chr17   81822665   81822966   chr17:81822816:A:G
123      ZNF397  chr18   35248508   35248809   chr18:35248659:A:G
124      TIMM29  chr19   10929979   10930280   chr19:10930130:A:G
125      ZNF844  chr19   12080824   12081125   chr19:12080975:A:G
126      MRI1-1  chr19   13773560   13773861   chr19:13773711:A:G
127      MRI1-2  chr19   13773607   13773908   chr19:13773758:A:G
128    ADGRE2-1  chr19   14734173   14734474   chr19:14734324:A:G
129    ADGRE2-2  chr19   14734509   14734810   chr19:14734660:A:G
130    ADGRE2-3  chr19   14734549   14734850   chr19:14734700:A:G
131    PGPEP1-1  chr19   18365245   18365546   chr19:18365396:A:G
132    PGPEP1-2  chr19   18366368   18366669   chr19:18366519:A:G
133    PGPEP1-3  chr19   18366449   18366750   chr19:18366600:A:G
134    PGPEP1-4  chr19   18366940   18367241   chr19:18367091:A:G
135      BORCS8  chr19   19177244   19177545   chr19:19177395:A:G
136    ZNF101-1  chr19   19682820   19683121   chr19:19682971:A:G
137    ZNF101-2  chr19   19682915   19683216   chr19:19683066:A:G
138    ZNF101-3  chr19   19682916   19683217   chr19:19683067:A:G
139         PVR  chr19   44663703   44664004   chr19:44663854:A:G
140     ZNF587B  chr19   57845749   57846050   chr19:57845900:A:G
141      POLR2D   chr2  127845935  127846236   chr2:127846086:A:G
142     CFLAR-1   chr2  201163853  201164154   chr2:201164004:A:G
143     CFLAR-2   chr2  201163859  201164160   chr2:201164010:A:G
144     CFLAR-3   chr2  201165220  201165521   chr2:201165371:A:G
145     CFLAR-4   chr2  201165395  201165696   chr2:201165546:A:G
146    CASP10-1   chr2  201217888  201218189   chr2:201218039:A:G
147    CASP10-2   chr2  201218183  201218484   chr2:201218334:A:G
148    CASP10-3   chr2  201218361  201218662   chr2:201218512:A:G
149    CASP10-4   chr2  201218371  201218672   chr2:201218522:A:G
150       CASP8   chr2  201287188  201287489   chr2:201287339:A:G
151   CYP20A1-1   chr2  203297723  203298024   chr2:203297874:A:G
152   CYP20A1-2   chr2  203300519  203300820   chr2:203300670:A:G
153   CYP20A1-3   chr2  203300618  203300919   chr2:203300769:A:G
154   CYP20A1-4   chr2  203305311  203305612   chr2:203305462:A:G
155    CCNYL1-1   chr2  207754586  207754887   chr2:207754737:A:G
156    CCNYL1-2   chr2  207754616  207754917   chr2:207754767:A:G
157    CCNYL1-3   chr2  207754800  207755101   chr2:207754951:A:G
158    CCNYL1-4   chr2  207754867  207755168   chr2:207755018:A:G
159       CXCR2   chr2  218135740  218136041   chr2:218135891:C:T
160       SGPP2   chr2  222559364  222559665   chr2:222559515:A:G
161       YIPF4   chr2   32310528   32310829    chr2:32310679:A:G
162   EIF2AK2-1   chr2   37100788   37101089    chr2:37100939:A:G
163   EIF2AK2-2   chr2   37100803   37101104    chr2:37100954:A:G
164   EIF2AK2-3   chr2   37103744   37104045    chr2:37103895:A:G
165   CEBPZOS-1   chr2   37202333   37202634    chr2:37202484:A:G
166   CEBPZOS-2   chr2   37202383   37202684    chr2:37202534:A:G
167    MRPL30-1   chr2   99195675   99195976    chr2:99195826:A:G
168    MRPL30-2   chr2   99195850   99196151    chr2:99196001:A:G
169    MRPL30-3   chr2   99196194   99196495    chr2:99196345:A:G
170    MRPL30-4   chr2   99196201   99196502    chr2:99196352:A:G
171    MRPL30-5   chr2   99196203   99196504    chr2:99196354:A:G
172    MRPL30-6   chr2   99196243   99196544    chr2:99196394:A:G
173    MRPL30-7   chr2   99196364   99196665    chr2:99196515:A:G
174    MRPL30-8   chr2   99196374   99196675    chr2:99196525:A:G
175     RBBP9-1  chr20   18487679   18487980   chr20:18487830:A:G
176     RBBP9-2  chr20   18488292   18488593   chr20:18488443:A:G
177      IFNAR2  chr21   33263905   33264206   chr21:33264056:A:G
178    IL17RA-1  chr22   17110226   17110527   chr22:17110377:A:G
179    IL17RA-2  chr22   17113117   17113418   chr22:17113268:A:G
180    SNRPD3-1  chr22   24573681   24573982   chr22:24573832:A:G
181    SNRPD3-2  chr22   24574423   24574724   chr22:24574574:A:G
182       TPST2  chr22   26523613   26523914   chr22:26523764:A:G
183     APOL6-1  chr22   35659740   35660041   chr22:35659891:A:G
184     APOL6-2  chr22   35660400   35660701   chr22:35660551:A:G
185     APOL6-3  chr22   35661053   35661354   chr22:35661204:A:G
186     APOL6-4  chr22   35661157   35661458   chr22:35661308:A:G
187     APOL1-1  chr22   36266069   36266370   chr22:36266220:A:G
188     APOL1-2  chr22   36266120   36266421   chr22:36266271:A:G
189     APOL1-3  chr22   36266199   36266500   chr22:36266350:A:G
190     APOL1-4  chr22   36266200   36266501   chr22:36266351:A:G
191     APOL1-5  chr22   36266592   36266893   chr22:36266743:A:G
192    APOBEC3C  chr22   39019735   39020036   chr22:39019886:A:G
193    APOBEC3F  chr22   39053367   39053668   chr22:39053518:A:G
194       DESI1  chr22   41599105   41599406   chr22:41599256:A:G
195       NFAM1  chr22   42383383   42383684   chr22:42383534:A:G
196    KIAA0930  chr22   45194257   45194558   chr22:45194408:A:G
197       VHL-1   chr3   10150949   10151250    chr3:10151100:A:G
198       VHL-2   chr3   10150981   10151282    chr3:10151132:A:G
199       NXPE3   chr3  101823441  101823742   chr3:101823592:A:G
200        RBSN   chr3   15072828   15073129    chr3:15072979:A:G
201        SSR3   chr3  156541423  156541724   chr3:156541574:A:G
202      GNB4-1   chr3  179399216  179399517   chr3:179399367:A:G
203      GNB4-2   chr3  179399225  179399526   chr3:179399376:A:G
204      GNB4-3   chr3  179399325  179399626   chr3:179399476:A:G
205      GNB4-4   chr3  179399327  179399628   chr3:179399478:A:G
206     LRCH3-1   chr3  197884189  197884490   chr3:197884340:A:G
207     LRCH3-2   chr3  197885198  197885499   chr3:197885349:A:G
208     LRCH3-3   chr3  197885246  197885547   chr3:197885397:A:G
209  KIAA1143-1   chr3   44748993   44749294    chr3:44749144:A:G
210  KIAA1143-2   chr3   44749754   44750055    chr3:44749905:A:G
211   PRKAR2A-1   chr3   48749458   48749759    chr3:48749609:A:G
212   PRKAR2A-2   chr3   48750272   48750573    chr3:48750423:A:G
213    ABHD18-1   chr4  128036424  128036725   chr4:128036575:A:G
214    ABHD18-2   chr4  128036779  128037080   chr4:128036930:A:G
215    SH3BP2-1   chr4    2839474    2839775     chr4:2839625:A:G
216    SH3BP2-2   chr4    2839510    2839811     chr4:2839661:A:G
217    SH3BP2-3   chr4    2839923    2840224     chr4:2840074:A:G
218    SH3BP2-4   chr4    2839967    2840268     chr4:2840118:A:G
219      PHAX-1   chr5  126625780  126626081   chr5:126625931:A:G
220      PHAX-2   chr5  126626332  126626633   chr5:126626483:A:G
221  ARHGAP26-1   chr5  143225101  143225402   chr5:143225252:A:G
222  ARHGAP26-2   chr5  143225290  143225591   chr5:143225441:A:G
223      ADAM19   chr5  157478401  157478702   chr5:157478552:A:G
224      SGTB-1   chr5   65668074   65668375    chr5:65668225:A:G
225      SGTB-2   chr5   65668348   65668649    chr5:65668499:A:G
226      SGTB-3   chr5   65668705   65669006    chr5:65668856:A:G
227      SGTB-4   chr5   65668740   65669041    chr5:65668891:A:G
228       ERAP1   chr5   96774689   96774990    chr5:96774840:A:G
229      ZBTB24   chr6  109462932  109463233   chr6:109463083:A:G
230       GINM1   chr6  149591020  149591321   chr6:149591171:A:G
231       NUP43   chr6  149724469  149724770   chr6:149724620:A:G
232     RSPH3-1   chr6  158974177  158974478   chr6:158974328:A:G
233     RSPH3-2   chr6  158974182  158974483   chr6:158974333:A:G
234     RSPH3-3   chr6  158974238  158974539   chr6:158974389:A:G
235      TRIM38   chr6   25990285   25990586    chr6:25990436:A:G
236      CGAS-1   chr6   73424840   73425141    chr6:73424991:A:G
237      CGAS-2   chr6   73424880   73425181    chr6:73425031:A:G
238      CGAS-3   chr6   73424885   73425186    chr6:73425036:A:G
239      CGAS-4   chr6   73424974   73425275    chr6:73425125:A:G
240     SLC17A5   chr6   73594139   73594440    chr6:73594290:A:G
241      TRIM56   chr7  101091366  101091667   chr7:101091517:A:G
242       RBM28   chr7  128307775  128308076   chr7:128307926:A:G
243     METTL2B   chr7  128502628  128502929   chr7:128502779:A:G
244       AHR-1   chr7   17344620   17344921    chr7:17344771:A:G
245       AHR-2   chr7   17344910   17345211    chr7:17345061:A:G
246       AHR-3   chr7   17344988   17345289    chr7:17345139:A:G
247       AHR-4   chr7   17345008   17345309    chr7:17345159:A:G
248       AHR-5   chr7   17345105   17345406    chr7:17345256:A:G
249      GPR141   chr7   37742668   37742969    chr7:37742819:A:G
250     VPS41-1   chr7   38724508   38724809    chr7:38724659:A:G
251     VPS41-2   chr7   38724571   38724872    chr7:38724722:A:G
252       TMED4   chr7   44580720   44581021    chr7:44580871:A:G
253        PPIA   chr7   44802178   44802479    chr7:44802329:A:G
254      CRCP-1   chr7   66154206   66154507    chr7:66154357:A:G
255      CRCP-2   chr7   66154209   66154510    chr7:66154360:A:G
256      CTSB-1   chr8   11842558   11842859    chr8:11842709:A:G
257      CTSB-2   chr8   11842936   11843237    chr8:11843087:A:G
258      CTSB-3   chr8   11843017   11843318    chr8:11843168:A:G
259      CTSB-4   chr8   11843769   11844070    chr8:11843920:A:G
260      CTSB-5   chr8   11843825   11844126    chr8:11843976:A:G
261        MSR1   chr8   16107995   16108296    chr8:16108146:A:G
262       GSR-1   chr8   30678307   30678608    chr8:30678458:A:G
263       GSR-2   chr8   30678312   30678613    chr8:30678463:A:G
264     PLEKHA2   chr8   38972169   38972470    chr8:38972320:A:G
265     HOOK3-1   chr8   43020432   43020733    chr8:43020583:A:G
266     HOOK3-2   chr8   43020442   43020743    chr8:43020593:A:G
267     HOOK3-3   chr8   43020774   43021075    chr8:43020925:A:G
268     HOOK3-4   chr8   43021252   43021553    chr8:43021403:A:G
269         LYN   chr8   56012445   56012746    chr8:56012596:A:G
270    TTC39B-1   chr9   15167178   15167479    chr9:15167329:A:G
271    TTC39B-2   chr9   15167539   15167840    chr9:15167690:A:G
272     ACOT9-1   chrX   23701520   23701821    chrX:23701671:A:G
273     ACOT9-2   chrX   23701756   23702057    chrX:23701907:A:G
274     ACOT9-3   chrX   23702386   23702687    chrX:23702537:A:G
275      ARSD-1   chrX    2906185    2906486     chrX:2906336:A:G
276      ARSD-2   chrX    2906282    2906583     chrX:2906433:A:G
277      ARSD-3   chrX    2906922    2907223     chrX:2907073:A:G
278     GNL3L-1   chrX   54562599   54562900    chrX:54562750:A:G
279     GNL3L-2   chrX   54564683   54564984    chrX:54564834:A:G
280     MAGT1-1   chrX   77827997   77828298    chrX:77828148:A:G
281     MAGT1-2   chrX   77828005   77828306    chrX:77828156:A:G
282     MAGT1-3   chrX   77828394   77828695    chrX:77828545:A:G

     Gene_Frequency  Edited_seq_num Edited_Index  \
0                 1             151            G
1                 3             151            G
2                 3             151            G
3                 3             151            G
4                 2             151            G
5                 2             151            G
6                 5             151            G
7                 5             151            G
8                 5             151            G
9                 5             151            G
10                5             151            G
11                1             151            G
12                1             151            G
13                2             151            G
14                2             151            G
15                1             151            G
16                1             151            G
17                8             151            G
18                8             151            G
19                8             151            G
20                8             151            G
21                8             151            G
22                8             151            G
23                8             151            G

In [7]:
lps_df_named = make_unique_gene_names(lps_df)
lps_df_named['Edited_seq'] =lps_df_named['Raw_seq']

In [27]:
list(ifnb_df_named)

['Gene',
 'Chr',
 'Start',
 'End',
 'Name',
 'Gene_Frequency',
 'Edited_seq_num',
 'Edited_Index',
 'Raw_seq',
 'Edited_seq']

In [9]:
def make_multi_edits(df_in):
    
    #df_in = ifnb_df_named
    multi_edit = df_in
    for gene, group in multi_edit.groupby('Gene'):
        # Making editing pairs by number and index 
        for seq_num, seq_index, edited_seq in zip(group['Edited_seq_num'], 
                                                  group['Edited_Index'], 
                                                  group['Edited_seq']):
            num_list = str(seq_num).split(',')
            index_list = seq_index.split(',')
            
            #print(num_list)
            #print(index_list)
            # Iterate over the pairs of edited sequence number and index
            for num, index in zip(num_list, index_list):
                #if num == 'PAIR':
                    #continue 
                # seq num -> integer
                num = int(num)
                # Update the corresponding Nth position in 'Edited_seq'
                edited_seq = edited_seq[:num-1] + index + edited_seq[num:]
                # Update the current gene's 'Edited_seq' to the generated updated 'edited_seq'
                multi_edit.loc[group.index, 'Edited_seq'] = edited_seq

    # rearrange Cols 
    multi_edit= multi_edit[['Gene','Chr','Start','End','Name','Gene_Frequency','Edited_seq_num',
                            'Edited_Index','Raw_seq','Edited_seq']]
    
    return multi_edit

In [41]:
ifnb_df_edit=make_multi_edits(ifnb_df_named)

#print(ifnb_df_edit[5, 'Raw_seq'])
#print(ifnb_df_edit[5, 'Edited_seq'])

['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['T']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['T']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['T']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']

In [10]:
lps_df_edit=make_multi_edits(lps_df_named)

['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']
['151']
['G']

In [42]:
ifnb_df_edit.iloc[:15]

,Gene,Chr,Start,End,Name,Gene_Frequency,Edited_seq_num,Edited_Index,Raw_seq,Edited_seq
0,NBPF15,chr1,144421990,144422291,chr1:144422141:A:G,1,151,G,TCGGTCTGTCGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTG...,TCGGTCTGTCGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTG...
1,NBPF14-1,chr1,148531982,148532283,chr1:148532133:A:G,3,151,G,TCGGTCTGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTG...,TCGGTCTGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTG...
2,NBPF14-2,chr1,148531988,148532289,chr1:148532139:A:G,3,151,G,TGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTGGTAGGT...,TGTCGACTGGACAGAAGATATTTGTTCAGGTACAGTGGTGGTAGGT...
3,NBPF14-3,chr1,148532058,148532359,chr1:148532209:A:G,3,151,G,TATAAACCCCAAGTTTTATTGATTTCTTTACGTCGATGTAATAGAA...,TATAAACCCCAAGTTTTATTGATTTCTTTACGTCGATGTAATAGAA...
4,NBPF20-1,chr1,149054639,149054940,chr1:149054790:A:G,2,151,G,TGTCGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTGGTAGGT...,TGTCGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTGGTAGGT...
5,NBPF20-2,chr1,149054642,149054943,chr1:149054793:A:G,2,151,G,CGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTGGTAGGTACT...,CGACTGGACAGGAGATATTTGTTCAGGTACAGTGGTGGTAGGTACT...
6,CTSS-1,chr1,150730985,150731286,chr1:150731136:A:G,5,151,G,ATTCTTCCGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTG...,ATTCTTCCGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTG...
7,CTSS-2,chr1,150730992,150731293,chr1:150731143:A:G,5,151,G,CGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTGGGTACAA...,CGTAAGTATCCGAAATTGTCTATCGATTTCTGATTCTTGGGTACAA...
8,CTSS-3,chr1,150731785,150732086,chr1:150731936:A:G,5,151,G,ACAACTACTGATGCATTTTTATTAAACCTGATTATGTAATTTAACA...,ACAACTACTGATGCATTTTTATTAAACCTGATTATGTAATTTAACA...
9,CTSS-4,chr1,150731958,150732259,chr1:150732109:A:G,5,151,G,ACGTCACCACGTTAATGTTCGAGTGACGTAAGAGTTGGAGGACCCG...,ACGTCACCACGTTAATGTTCGAGTGACGTAAGAGTTGGAGGACCCG...
10,CTSS-5,chr1,150732621,150732922,chr1:150732772:A:G,5,151,G,AAAACTTTGTCTCAGAGGTGAGACAGTAGGTCCGACCTCATGTCAC...,AAAACTTTGTCTCAGAGGTGAGACAGTAGGTCCGACCTCATGTCAC...
11,F11R,chr1,160997892,160998193,chr1:160998043:A:G,1,151,G,GTTTTCCCAGACAGGTCATCAAGGTCGGTTCCCTTCCCACTACCGG...,GTTTTCCCAGACAGGTCATCAAGGTCGGTTCCCTTCCCACTACCGG...
12,SLC35E2B,chr1,1663996,1664297,chr1:1664147:A:G,1,151,G,GGACCCGTTGTTTCGCTCTCGGGTCGAGTTGTTTTTTTATCGGTCC...,GGACCCGTTGTTTCGCTCTCGGGTCGAGTTGTTTTTTTATCGGTCC...
13,SOAT1-1,chr1,179357488,179357789,chr1:179357639:A:G,2,151,G,TGCTCCCGGCCAAAGTGAATGTTTTGGGTGAAGTTTATATAAGGAT...,TGCTCCCGGCCAAAGTGAATGTTTTGGGTGAAGTTTATATAAGGAT...
14,SOAT1-2,chr1,179357593,179357894,chr1:179357744:A:G,2,151,G,AAATAAAATGTTACATATCGCTGGGTGTAGTGGCTCATGCCTTTAA...,AAATAAAATGTTACATATCGCTGGGTGTAGTGGCTCATGCCTTTAA...

### What has to be added is a GPNMB MFE without any editing. just the Raw seq of GPNMB with + stranding should be input to the RNAfold

In [48]:
# [row, Raw_seq][n-1]
raw = ifnb_df_edit.loc[8, 'Raw_seq'][150]
edit =ifnb_df_edit.loc[8, 'Edited_seq'][150]
print(raw)
print(edit)

A
G

In [49]:
ifnb_df_edit.loc[8, 'Raw_seq']

'ACAACTACTGATGCATTTTTATTAAACCTGATTATGTAATTTAACAACTAGTAATTTTATTAAGAAGGTTTCACGAACAGAAAATACGTAAAGAAATGAAATTGTATTATATTTTTATACACAACTTAGGAGAAAAAAATTCTGTCCCAGAACGAGACAGTGGGTCCGACCTCACGTCACCACGTTAATGTTCGAGTGACGTAAGAGTTGGAGGACCCGAGAACACTAGGAGGACAGAATCTGTAGACGTATCGTCCCTGGTGTCCGTGTGTGGTGGTGAGGACCTATCAAAGAAAAAATA'

In [50]:
ifnb_df_edit.loc[8, 'Edited_seq']

'ACAACTACTGATGCATTTTTATTAAACCTGATTATGTAATTTAACAACTAGTAATTTTATTAAGAAGGTTTCACGAACAGAAAATACGTAAAGAAATGAAATTGTATTATATTTTTATACACAACTTAGGAGAAAAAAATTCTGTCCCAGGACGAGACAGTGGGTCCGACCTCACGTCACCACGTTAATGTTCGAGTGACGTAAGAGTTGGAGGACCCGAGAACACTAGGAGGACAGAATCTGTAGACGTATCGTCCCTGGTGTCCGTGTGTGGTGGTGAGGACCTATCAAAGAAAAAATA'

In [51]:
ifnb_df_edit.to_csv('/Users/hyominseo/Desktop/RAJ_RNA_Editing/MFE/Edited_fasta/Edited_All_MPRA_IFNb_Ed_Sites.tsv')

In [14]:
raw = lps_df_edit.loc[8, 'Raw_seq'][150]
edit =lps_df_edit.loc[8, 'Edited_seq'][150]
print(raw)
print(edit)

A
G

In [15]:
lps_df_edit.loc[8,'Raw_seq']

'AAATAAAATGTTACATATCGCTGGGTGTAGTGGCTCATGCCTTTAATCCCAGTACTTTGGGAGGCCAAGGCAGGAGGATTGCTTGAGCTCAGAAGTTTGAGACCAGCCTGGGCAACATAGCAAAACCTTGTCACTATAAAAAATACAAAAATTAGCCAGGCGTGGTGGTGCACGCCTGTAGTCTCAGCTACTCAGTCGGCTGAGGTGGGAAGATGGCTTCAAGCCGGGAGATGGAGGCTTCAGTGACCTGTGACCTGTGATCACACCACTTAATTCCTCAAAACATTTATGTCCCAGTTCC'

In [16]:
lps_df_edit.loc[8,'Edited_seq']

'AAATAAAATGTTACATATCGCTGGGTGTAGTGGCTCATGCCTTTAATCCCAGTACTTTGGGAGGCCAAGGCAGGAGGATTGCTTGAGCTCAGAAGTTTGAGACCAGCCTGGGCAACATAGCAAAACCTTGTCACTATAAAAAATACAAAAGTTAGCCAGGCGTGGTGGTGCACGCCTGTAGTCTCAGCTACTCAGTCGGCTGAGGTGGGAAGATGGCTTCAAGCCGGGAGATGGAGGCTTCAGTGACCTGTGACCTGTGATCACACCACTTAATTCCTCAAAACATTTATGTCCCAGTTCC'

In [17]:
lps_df_edit.to_csv('/Users/hyominseo/Desktop/RAJ_RNA_Editing/MFE/Edited_fasta/Edited_All_MPRA_LPS_Ed_Sites.tsv')